name: dev CI

on:
    pull_request:
        branches: [develop]

jobs:
    ci_for_develop_based_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 20
                  cache: 'yarn'
                  cache-dependency-path: './yarn.lock'
            - run: yarn install
            - run: yarn lint:check
            - run: yarn prettier:check
            - run: yarn build
