import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReduxProviders } from '@/@projectName/services/redux/ReduxProvider';
import AppThemeProvider from '@/@projectName/context/AppThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<AppThemeProvider>
				<ReduxProviders>
					<body className={inter.className}>{children}</body>
				</ReduxProviders>
			</AppThemeProvider>
		</html>
	);
}
